export const exampleSkillTemplate = `
const skill = {
  id: "skill_example",
  name: "Example Evolved Skill",
  description: "A safe, narrow skill template generated by the self-evolving engine.",
  kind: "general",
  version: "1.0.0",
  tags: ["evolution", "example", "safe"],
  enabled: true,

  canHandle(input, ctx) {
    const text = String(input || "").toLowerCase();
    if (text.includes("example") || text.includes("demo")) return 0.95;
    if (ctx && ctx.input && String(ctx.input).toLowerCase().includes("example")) return 0.85;
    return 0.1;
  },

  async run(ctx) {
    const input = String(ctx?.input || "");
    return {
      ok: true,
      message: "Example evolved skill ran successfully.",
      input,
      sessionId: ctx?.sessionId || "unknown",
      summary: \`Handled input: \${input}\`,
    };
  },
};

module.exports = { skill };
`;
