import type { EvolutionPromptContext, GeneratedSkillSpec, SkillTestCase } from "./types.js";

export function buildSkillGenerationPrompt(ctx: EvolutionPromptContext): string {
  const currentSkills = ctx.currentSkills.length
    ? ctx.currentSkills
        .map((s) => `- ${s.id}: ${s.name} — ${s.description} [${(s.tags ?? []).join(", ")}]`)
        .join("\n")
    : "none";

  const reflections = ctx.recentReflections?.length
    ? ctx.recentReflections
        .slice(0, 10)
        .map(
          (r) =>
            `- turn=${r.sourceTurnId} task=${r.taskType} outcome=${r.outcome} rootCause=${r.rootCause} correctiveAdvice=${r.correctiveAdvice} nextBestAction=${r.nextBestAction}`
        )
        .join("\n")
    : "none";

  return [
    "You are generating a SINGLE new TypeScript skill for CLAW_MACHINE.",
    "The skill must be safe, deterministic, and self-contained.",
    "Do not use network access, filesystem access, child_process, or dynamic imports.",
    "Export the skill as either `export default skill` or `module.exports = { skill }`.",
    "The skill object must implement: id, name, description, tags, kind, version, canHandle(input, ctx), run(ctx).",
    "The run function must return a string or a JSON-serializable object.",
    "",
    `Task description: ${ctx.task}`,
    `Domain hint: ${ctx.domainHint ?? "general"}`,
    "",
    "Current skills already in the system:",
    currentSkills,
    "",
    "Recent reflections from the self-improving loop:",
    reflections,
    "",
    "Add value by specializing in one narrow behavior, not by being generic.",
    "Prefer a skill that can be unit tested automatically.",
    "Keep the code readable and under ~250 lines if possible.",
  ].join("\n");
}

export function buildSkillRepairPrompt(args: {
  task: string;
  source: string;
  testFailures: string;
  scoreSummary: string;
  currentSkills: EvolutionPromptContext["currentSkills"];
}): string {
  const currentSkills = args.currentSkills.length ? args.currentSkills.map((s) => `- ${s.id}: ${s.name}`).join("\n") : "none";

  return [
    "You are repairing a TypeScript skill for CLAW_MACHINE.",
    "Keep the public shape the same unless absolutely required.",
    "Fix only what is necessary to make the tests pass and improve safety.",
    "Do not add risky APIs or external dependencies.",
    "",
    `Task: ${args.task}`,
    `Score summary: ${args.scoreSummary}`,
    "Test failures:",
    args.testFailures,
    "",
    "Existing skills:",
    currentSkills,
    "",
    "Original source:",
    args.source,
    "",
    "Return only the repaired TypeScript source.",
  ].join("\n");
}

export function buildTestGenerationPrompt(args: {
  task: string;
  spec: GeneratedSkillSpec;
  source: string;
  currentSkills?: Array<Pick<GeneratedSkillSpec, "id" | "name" | "description" | "tags" | "kind" | "version">>;
}): string {
  const currentSkills = args.currentSkills?.length
    ? args.currentSkills.map((s) => `- ${s.id}: ${s.name} — ${s.description}`).join("\n")
    : "none";

  return [
    "You are generating compact JSON test cases for a single TypeScript skill.",
    "The output must be valid JSON array only.",
    "Each test case must include: id, name, input, ctx, expect, weight.",
    "Do not include commentary.",
    "",
    `Task: ${args.task}`,
    `Skill spec: ${JSON.stringify(args.spec, null, 2)}`,
    "",
    "Existing skills for context:",
    currentSkills,
    "",
    "Source:",
    args.source,
    "",
    "Prefer a mix of handle checks, string inclusion checks, and edge cases.",
  ].join("\n");
}

export function fallbackSkillSpec(task: string, domainHint?: string): GeneratedSkillSpec {
  const slug =
    task
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 42) || "evolved_skill";

  return {
    id: `skill_${slug}`,
    name: toTitleCase(task),
    description: `Autogenerated skill for ${task}`,
    kind: inferKind(task, domainHint),
    tags: normalizeTags([domainHint ?? "evolution", "autogenerated", "self-evolving"]),
    version: "1.0.0",
    goal: task,
    inputs: ["input text", "skill execution context"],
    outputs: ["string", "json-serializable object"],
    constraints: ["No network access", "No filesystem access", "Deterministic behavior", "Safe sandbox execution"],
    acceptanceCriteria: [
      "canHandle returns a score for relevant inputs",
      "run returns a useful answer",
      "tests pass in sandbox",
      "skill can hot-register into the live registry",
    ],
    examples: [
      {
        input: task,
        expectedBehavior: "The skill should handle the task and produce a targeted result.",
      },
    ],
  };
}

function generateFallbackTests(spec: GeneratedSkillSpec): SkillTestCase[] {
  const positive = spec.examples[0]?.input ?? spec.goal;
  return [
    {
      id: `${spec.id}_handle_positive`,
      name: "handles the primary use case",
      input: positive,
      ctx: { requestId: "test_1", sessionId: "session_test", input: positive },
      expect: {
        shouldHandle: true,
        minHandleScore: 0.5,
      },
      weight: 2,
    },
    {
      id: `${spec.id}_run_positive`,
      name: "returns a useful output",
      input: positive,
      ctx: { requestId: "test_2", sessionId: "session_test", input: positive },
      expect: {
        outputIncludes: positive.split(/\s+/).slice(0, 3).filter(Boolean),
      },
      weight: 3,
    },
    {
      id: `${spec.id}_handle_unrelated`,
      name: "does not overclaim unrelated input",
      input: "banana apple cloud mountain",
      ctx: { requestId: "test_3", sessionId: "session_test", input: "banana apple cloud mountain" },
      expect: {
        shouldHandle: false,
        maxHandleScore: 0.35,
      },
      weight: 1,
    },
  ];
}

function inferKind(task: string, domainHint?: string): GeneratedSkillSpec["kind"] {
  const text = `${task} ${domainHint ?? ""}`.toLowerCase();
  if (text.includes("memory") || text.includes("recall") || text.includes("retrieve")) return "retrieval";
  if (text.includes("wallet") || text.includes("tx") || text.includes("transaction")) return "wallet";
  if (text.includes("reflect") || text.includes("lesson") || text.includes("mistake")) return "reflection";
  if (text.includes("store") || text.includes("persist") || text.includes("archive")) return "storage";
  if (text.includes("plan") || text.includes("route") || text.includes("strategy")) return "planner";
  if (text.includes("safe") || text.includes("policy") || text.includes("risk")) return "safety";
  if (text.includes("analyze") || text.includes("debug") || text.includes("inspect")) return "analysis";
  if (text.includes("execute") || text.includes("run") || text.includes("perform")) return "execution";
  return "general";
}

function normalizeTags(tags: string[]): string[] {
  return [...new Set(tags.map((t) => t.trim().toLowerCase()).filter(Boolean))];
}

function toTitleCase(text: string): string {
  return text
    .replace(/[_-]+/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
