export const skillRegistryAbi = [
  "function registerSkill((address owner,string namespace,string name,string description,string implementationUri,string metadataUri,string storageUri,string computeModel,string entrypoint,bytes32 inputSchemaHash,bytes32 outputSchemaHash,bytes32 codeHash,bool requiresWallet,bool requiresApproval,bool publicUse,uint256 feeBps,string pinnedStorageUri,string pinnedComputeUri,string explorerUri,address implementationAddress,bytes32 metadataHash,string[] tags,string[] capabilityHints) input) external returns (bytes32)",
  "function registerSkillForOwner((address owner,string namespace,string name,string description,string implementationUri,string metadataUri,string storageUri,string computeModel,string entrypoint,bytes32 inputSchemaHash,bytes32 outputSchemaHash,bytes32 codeHash,bool requiresWallet,bool requiresApproval,bool publicUse,uint256 feeBps,string pinnedStorageUri,string pinnedComputeUri,string explorerUri,address implementationAddress,bytes32 metadataHash,string[] tags,string[] capabilityHints) input) external returns (bytes32)",
  "function addSkillVersion(bytes32 skillId,(string implementationUri,string metadataUri,string storageUri,string computeModel,string entrypoint,bytes32 inputSchemaHash,bytes32 outputSchemaHash,bytes32 codeHash,bool requiresWallet,bool requiresApproval,bool publicUse,address implementationAddress,bytes32 metadataHash,string[] tags,string[] capabilityHints) input) external returns (uint256)",
  "function activateSkillVersion(bytes32 skillId,uint256 version) external",
  "function disableSkillVersion(bytes32 skillId,uint256 version) external",
  "function deprecateSkill(bytes32 skillId,string reason) external",
  "function pauseSkill(bytes32 skillId) external",
  "function unpauseSkill(bytes32 skillId) external",
  "function approveSkill(bytes32 skillId,bool approved) external",
  "function approveOperator(bytes32 skillId,address operator) external",
  "function revokeOperator(bytes32 skillId,address operator) external",
  "function grantCurator(bytes32 skillId,address curator) external",
  "function revokeCurator(bytes32 skillId,address curator) external",
  "function transferSkillOwnership(bytes32 skillId,address newOwner) external",
  "function pinSkill(bytes32 skillId,string storageUri,string computeUri,bytes32 metadataHash) external",
  "function setExplorerUri(bytes32 skillId,string explorerUri) external",
  "function reportUsage(bytes32 skillId,bool success,uint256 latencyMs,bytes32 runHash) external",
  "function getSkill(bytes32 skillId) external view returns ((bytes32 skillId,address owner,string namespace,string name,string description,uint8 status,uint256 activeVersion,uint256 latestVersion,uint256 createdAt,uint256 updatedAt,uint256 totalUsage,uint256 totalSuccesses,uint256 totalFailures,uint256 averageLatencyMs,uint256 feeBps,bool allowPublicUse,bool approved,bool pinnedTo0G,string pinnedStorageUri,string pinnedComputeUri,string explorerUri,address implementationAddress,address lastUpdatedBy,bytes32 metadataHash))",
  "function getSkillById(bytes32 skillId) external view returns (((bytes32 skillId,address owner,string namespace,string name,string description,uint8 status,uint256 activeVersion,uint256 latestVersion,uint256 createdAt,uint256 updatedAt,uint256 totalUsage,uint256 totalSuccesses,uint256 totalFailures,uint256 averageLatencyMs,uint256 feeBps,bool allowPublicUse,bool approved,bool pinnedTo0G,string pinnedStorageUri,string pinnedComputeUri,string explorerUri,address implementationAddress,address lastUpdatedBy,bytes32 metadataHash), (uint256 version,string implementationUri,string metadataUri,string storageUri,string computeModel,string entrypoint,bytes32 inputSchemaHash,bytes32 outputSchemaHash,bytes32 codeHash,bool requiresWallet,bool requiresApproval,bool publicUse,bool enabled,uint256 createdAt,uint256 updatedAt,string[] tags,string[] capabilityHints), (uint256 successCount,uint256 failureCount,uint256 totalLatencyMs,uint256 lastUsedAt,bytes32 lastRunHash)))",
  "function getSkillVersion(bytes32 skillId,uint256 version) external view returns ((uint256 version,string implementationUri,string metadataUri,string storageUri,string computeModel,string entrypoint,bytes32 inputSchemaHash,bytes32 outputSchemaHash,bytes32 codeHash,bool requiresWallet,bool requiresApproval,bool publicUse,bool enabled,uint256 createdAt,uint256 updatedAt,string[] tags,string[] capabilityHints))",
  "function getAllVersions(bytes32 skillId) external view returns (uint256[])",
  "function getSkillIds((uint256 offset,uint256 limit) page) external view returns (bytes32[])",
  "function getSkillsByOwner(address owner,(uint256 offset,uint256 limit) page) external view returns (bytes32[])",
  "function getUsage(bytes32 skillId) external view returns ((uint256 successCount,uint256 failureCount,uint256 totalLatencyMs,uint256 lastUsedAt,bytes32 lastRunHash))",
  "function skillExists(bytes32 skillId) external view returns (bool)",
  "function isApprovedOperator(bytes32 skillId,address operator) external view returns (bool)",
  "function isCurator(bytes32 skillId,address account) external view returns (bool)",
  "function isSkillReady(bytes32 skillId) external view returns (bool)",
  "function totalSkills() external view returns (uint256)",
  "event SkillRegistered(bytes32 indexed skillId,address indexed owner,string namespace,string name,uint256 version,address implementationAddress,bytes32 metadataHash)",
  "event SkillVersionAdded(bytes32 indexed skillId,uint256 indexed version,address indexed owner,address implementationAddress,bytes32 metadataHash)",
  "event SkillActivated(bytes32 indexed skillId,uint256 indexed version,address indexed operator)",
  "event SkillPaused(bytes32 indexed skillId,address indexed operator)",
  "event SkillDeprecated(bytes32 indexed skillId,address indexed operator)",
  "event SkillRevoked(bytes32 indexed skillId,address indexed operator,string reason)",
  "event SkillApproved(bytes32 indexed skillId,address indexed approver,bool approved)",
  "event SkillOwnershipTransferred(bytes32 indexed skillId,address indexed previousOwner,address indexed newOwner)",
  "event SkillUsageReported(bytes32 indexed skillId,address indexed reporter,bool success,uint256 latencyMs,bytes32 runHash)",
  "event SkillPinned(bytes32 indexed skillId,string storageUri,string computeUri,bytes32 metadataHash)",
  "event CuratorGranted(bytes32 indexed skillId,address indexed curator)",
  "event CuratorRevoked(bytes32 indexed skillId,address indexed curator)",
  "event OperatorApproved(bytes32 indexed skillId,address indexed operator)",
  "event OperatorRevoked(bytes32 indexed skillId,address indexed operator)",
] as const;
