#!/usr/bin/env node
/**
 * @claw/cli
 *
 * Command-line interface for the CLAW_MACHINE framework.
 *
 * Commands:
 *   claw init <name>           Scaffold a new agent project
 *   claw skill add <id>        Generate a new skill stub
 *   claw plugin add <id>       Generate a new plugin stub
 *   claw dev                   Start the development server
 *   claw info                  Print framework version and config
 */

import { mkdir, writeFile, readFile } from "fs/promises";
import { existsSync } from "fs";
import { join, resolve } from "path";
import { execSync } from "child_process";

const VERSION = "0.1.0";
const args = process.argv.slice(2);

// ── Templates ─────────────────────────────────────────────────────────────────

const SKILL_TEMPLATE = (id: string, name: string) => `/**
 * ${name} Skill
 * Auto-generated by @claw/cli
 */
import { defineSkill } from "@claw/core";

export const ${toCamel(id)}Skill = defineSkill({
  manifest: {
    id: "${id}",
    name: "${name}",
    description: "TODO: describe what this skill does",
    tags: ["custom"],
    requiresWallet: false,
    touchesChain: false,
    usesCompute: false,
    usesStorage: false,
  },
  async execute(input, ctx) {
    // TODO: implement skill logic
    // ctx.memory   — read/write memory
    // ctx.compute  — call LLM or embeddings
    // ctx.storage  — read/write 0G Storage
    // ctx.emit(event, payload) — emit framework events

    return {
      output: \`Executed ${name} with input: \${JSON.stringify(input)}\`,
    };
  },
});
`;

const PLUGIN_TEMPLATE = (id: string, name: string) => `/**
 * ${name} Plugin
 * Auto-generated by @claw/cli
 */
import { definePlugin } from "@claw/core";

export const ${toCamel(id)}Plugin = definePlugin({
  id: "${id}",
  name: "${name}",
  version: "0.1.0",
  description: "TODO: describe what this plugin does",
  hooks: {
    onAgentInit(agent) {
      console.log("[${id}] Plugin initialized");
    },

    onBeforeTurn(input) {
      // Optionally mutate input before the agent processes it
      return input;
    },

    onAfterTurn(result) {
      // Optionally mutate result after the agent processes it
      return result;
    },

    onError(error, phase) {
      console.error(\`[${id}] Error in \${phase}:\`, error.message);
    },
  },
});
`;

const AGENT_TEMPLATE = (name: string) => `/**
 * ${name} — Main agent entry point
 * Generated by @claw/cli
 */
import { AgentBuilder } from "@claw/core";
import { zeroGPlugin } from "@claw/plugin-0g";
import { openClawPlugin } from "@claw/plugin-openclaw";
// import { mySkill } from "./skills/mySkill.js";

async function main() {
  const agent = await new AgentBuilder()
    .setName("${name}")
    .setSystemPrompt("You are a helpful AI agent running on the 0G network.")
    .use(zeroGPlugin({
      rpc: process.env.EVM_RPC ?? "https://evmrpc-testnet.0g.ai",
      privateKey: process.env.PRIVATE_KEY,
      computeModel: process.env.COMPUTE_MODEL ?? "qwen3.6-plus",
    }))
    .use(openClawPlugin())
    // .skill(mySkill)
    .enableReflection()
    .enablePruning()
    .build();

  console.log("Agent ready. Skills:", agent.listSkills().map(s => s.id));

  const result = await agent.run({
    message: "Hello! What can you do?",
  });
  console.log("\\nAgent:", result.output);
  console.log("Trace:", result.trace.map(t => \`\${t.phase}(\${t.durationMs}ms)\`).join(" → "));

  await agent.destroy();
}

main().catch(console.error);
`;

const ENV_TEMPLATE = `# CLAW_MACHINE Framework — Environment Variables
# Copy to .env and fill in your values

# 0G Network
EVM_RPC=https://evmrpc-testnet.0g.ai
INDEXER_RPC=https://indexer-storage-testnet-turbo.0g.ai
COMPUTE_RPC=https://compute-testnet.0g.ai
COMPUTE_MODEL=qwen3.6-plus

# Wallet (optional — enables production 0G Storage/Compute)
PRIVATE_KEY=

# OpenAI-compatible fallback
OPENAI_API_KEY=
OPENAI_BASE_URL=https://api.openai.com/v1
OPENAI_MODEL=gpt-4o-mini

# Server
PORT=3001
NODE_ENV=development
CLAW_DEBUG=false
`;

const PACKAGE_TEMPLATE = (name: string) => JSON.stringify({
  name: name.toLowerCase().replace(/\s+/g, "-"),
  version: "0.1.0",
  description: `${name} — built with @claw/core`,
  type: "module",
  scripts: {
    dev: "tsx src/agent.ts",
    build: "tsc",
    start: "node dist/agent.js",
  },
  dependencies: {
    "@claw/core": "^0.1.0",
    "@claw/plugin-0g": "^0.1.0",
    "@claw/plugin-openclaw": "^0.1.0",
  },
  devDependencies: {
    typescript: "^5.3.0",
    tsx: "^4.7.0",
    "@types/node": "^20.0.0",
  },
}, null, 2);

const TSCONFIG_TEMPLATE = JSON.stringify({
  compilerOptions: {
    target: "ES2022",
    module: "NodeNext",
    moduleResolution: "NodeNext",
    strict: true,
    esModuleInterop: true,
    outDir: "dist",
    rootDir: "src",
  },
  include: ["src/**/*"],
}, null, 2);

// ── Utilities ─────────────────────────────────────────────────────────────────

function toCamel(str: string): string {
  return str.replace(/[.\-_/](.)/g, (_, c: string) => c.toUpperCase());
}

function toTitle(str: string): string {
  return str
    .split(/[.\-_/\s]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function log(msg: string) { console.log(`\x1b[36m[claw]\x1b[0m ${msg}`); }
function ok(msg: string)  { console.log(`\x1b[32m  ✓\x1b[0m ${msg}`); }
function err(msg: string) { console.error(`\x1b[31m  ✗\x1b[0m ${msg}`); }

// ── Commands ──────────────────────────────────────────────────────────────────

async function cmdInit(name: string) {
  const dir = resolve(process.cwd(), name);
  if (existsSync(dir)) { err(`Directory "${name}" already exists.`); process.exit(1); }

  log(`Scaffolding new agent project: ${name}`);
  await mkdir(join(dir, "src", "skills"), { recursive: true });
  await mkdir(join(dir, "src", "plugins"), { recursive: true });

  await writeFile(join(dir, "src", "agent.ts"), AGENT_TEMPLATE(toTitle(name)));
  await writeFile(join(dir, ".env.example"), ENV_TEMPLATE);
  await writeFile(join(dir, "package.json"), PACKAGE_TEMPLATE(name));
  await writeFile(join(dir, "tsconfig.json"), TSCONFIG_TEMPLATE);
  await writeFile(join(dir, ".gitignore"), "node_modules/\ndist/\n.env\n");
  await writeFile(join(dir, "README.md"), `# ${toTitle(name)}\n\nBuilt with [@claw/core](https://github.com/your-org/claw-machine).\n\n## Quick start\n\n\`\`\`bash\ncp .env.example .env\nnpm install\nnpm run dev\n\`\`\`\n`);

  ok(`Created ${name}/src/agent.ts`);
  ok(`Created ${name}/package.json`);
  ok(`Created ${name}/.env.example`);
  ok(`Created ${name}/tsconfig.json`);

  console.log(`\n\x1b[1mNext steps:\x1b[0m`);
  console.log(`  cd ${name}`);
  console.log(`  cp .env.example .env`);
  console.log(`  npm install`);
  console.log(`  npm run dev`);
}

async function cmdSkillAdd(id: string) {
  const skillsDir = resolve(process.cwd(), "src", "skills");
  if (!existsSync(skillsDir)) {
    await mkdir(skillsDir, { recursive: true });
  }
  const file = join(skillsDir, `${id}.ts`);
  if (existsSync(file)) { err(`Skill "${id}" already exists at ${file}`); process.exit(1); }
  await writeFile(file, SKILL_TEMPLATE(id, toTitle(id)));
  ok(`Created src/skills/${id}.ts`);
  console.log(`\nImport it in your agent:\n  import { ${toCamel(id)}Skill } from "./skills/${id}.js";\n  builder.skill(${toCamel(id)}Skill)`);
}

async function cmdPluginAdd(id: string) {
  const pluginsDir = resolve(process.cwd(), "src", "plugins");
  if (!existsSync(pluginsDir)) {
    await mkdir(pluginsDir, { recursive: true });
  }
  const file = join(pluginsDir, `${id}.ts`);
  if (existsSync(file)) { err(`Plugin "${id}" already exists at ${file}`); process.exit(1); }
  await writeFile(file, PLUGIN_TEMPLATE(id, toTitle(id)));
  ok(`Created src/plugins/${id}.ts`);
  console.log(`\nImport it in your agent:\n  import { ${toCamel(id)}Plugin } from "./plugins/${id}.js";\n  builder.use(${toCamel(id)}Plugin)`);
}

async function cmdDev() {
  const agentFile = resolve(process.cwd(), "src", "agent.ts");
  if (!existsSync(agentFile)) {
    err("No src/agent.ts found. Run `claw init <name>` first.");
    process.exit(1);
  }
  log("Starting development server...");
  try {
    execSync("npx tsx --watch src/agent.ts", { stdio: "inherit" });
  } catch {
    err("Failed to start dev server. Make sure tsx is installed: npm install -D tsx");
  }
}

function cmdInfo() {
  console.log(`\n\x1b[1m@claw/cli\x1b[0m v${VERSION}`);
  console.log(`\nUsage:`);
  console.log(`  claw init <name>       Scaffold a new agent project`);
  console.log(`  claw skill add <id>    Generate a skill stub`);
  console.log(`  claw plugin add <id>   Generate a plugin stub`);
  console.log(`  claw dev               Start development server`);
  console.log(`  claw info              Print this help\n`);
}

// ── Router ────────────────────────────────────────────────────────────────────

async function main() {
  const [cmd, sub, arg] = args;

  if (!cmd || cmd === "info" || cmd === "--help" || cmd === "-h") {
    cmdInfo();
    return;
  }

  if (cmd === "init") {
    if (!sub) { err("Usage: claw init <name>"); process.exit(1); }
    await cmdInit(sub);
    return;
  }

  if (cmd === "skill" && sub === "add") {
    if (!arg) { err("Usage: claw skill add <id>"); process.exit(1); }
    await cmdSkillAdd(arg);
    return;
  }

  if (cmd === "plugin" && sub === "add") {
    if (!arg) { err("Usage: claw plugin add <id>"); process.exit(1); }
    await cmdPluginAdd(arg);
    return;
  }

  if (cmd === "dev") {
    await cmdDev();
    return;
  }

  err(`Unknown command: ${cmd}`);
  cmdInfo();
  process.exit(1);
}

main().catch((e) => { console.error(e); process.exit(1); });
